### ISSUE TITLE
how to set the img name to date-time format without set name everytime

### ISSUE THREAD

**Issue by geeker-one** [TobinPalmer/pastify.nvim#4]
For example,how to set every image name to "%Y-%m-%d-%H-%M-%S.jpg"?

**Comment by geeker-one** [comment]
done,change the code in `if file_name == "":` as this:
```python
            if file_name == "":
                file_name=vim.exec_lua("return os.date('%Y-%m-%d-%H:%M:%S')")
                self.logger(f"use date as filename:{file_name}", "INFO")
```
however, can you add a setting in config that we can set filename as date as preference?

**Comment by TobinPalmer** [comment]
Ok I will add this to my todo although I don't really use this plugin / nvim as much as I used to.

**Comment by superzanti** [comment]
Hi @geeker-one I created a [pull request](https://github.com/TobinPalmer/pastify.nvim/pull/9) that fixes this issue and adds some other features.

**Comment by TobinPalmer** [comment]
This issue was solved by @geeker-one amazing PR.
