### ISSUE TITLE
feature request: work with GIF

### ISSUE THREAD

**Issue by Kamilcuk** [TobinPalmer/pastify.nvim#6]
I sometimes do gifs recordings with peek.

Would be great, if when Pastify is executed, if the clipboard _text_ matches a image extension, like `*.gif` or `file://*.gif` or `*.jpg` or any other image extension, it would just take this text as a filename and copy it into assets directory and insert the Markdown text.

On another small note, could add text to README like "To use this plugin, use :Pastify command, which will take the clipboard content and paste it". There are two movies, but no text description, only installation and config, it got me confused for a second.

Thanks! Great plugin!

**Comment by TobinPalmer** [comment]
thank you for your issue.

As for the first part, basically, I don't know if this is possible. I basically copied a GIF and pasted it into the pastify with this debugging code.

```py
    def paste_text(self) -> None:
        options = self.config['opts']
        img = ImageGrab.grabclipboard()
        if img is None:
            self.logger(
                "No image in clipboard.", "WARN")
            return

        img_name = img.format

        self.logger(f"image format: {img_name}", "INFO") # Always PNG
```

as you can see, this should print GIF if it is one but from lots of different file types it converts them to a png with metadata. If I could access that metadata than I could probably figure out the type.

As for the second issue I will update the readme now.

**Comment by TobinPalmer** [comment]
Also I would like to add that this was the exif of the image for many different images and types.

ResolutionUnit:2
ExifOffset:78
XResolution:144.0
YResolution:144.0

```py
        image_exif = img.getexif()
        if image_exif is None:
            print('Sorry, image has no exif data.')
        else:
            for key, val in image_exif.items():
                if key in ExifTags.TAGS:
                    with open(f"...", "a") as f:
                        f.write(f'{ExifTags.TAGS[key]}:{val}\n')
                else:
                    with open(f"...", "a") as f:
                        f.write(f'{key}:{val}\n')
```
