### ISSUE TITLE
Breaks when current working directory != file parent directory

### ISSUE THREAD

**Issue by nathom** [TobinPalmer/pastify.nvim#7]
The assets/img directory is added to the current working directory, but the file being edited need not be inside the root directory. In this case, an incorrect path will be added.

For example, if the cwd is `~/docs` and the file being edited is `~/docs/file1.tex`, the image directory will be created in `~/docs/assets` and the path added to the file will be `./assets/imgs/something.png`. The correct path would be `../assets/imgs/something.png`.

Another solution would be to put `assets/` in the current file's parent directory. This bug breaks pastify for anyone using a rooter plugin.

**Comment by superzanti** [comment]
@nathom I had this same issue and created an update (via my [pull request](https://github.com/TobinPalmer/pastify.nvim/pull/9)  ) to this project to address this issue and add some other features.

**Comment by TobinPalmer** [comment]
This issue was solved by @geeker-one amazing PR.
