### ISSUE TITLE
2 buffers open (one html one markdown) results in wrong formatting

### ISSUE THREAD

**Issue by superzanti** [TobinPalmer/pastify.nvim#8]
If I have 2 different buffers open with the same nvim instance, since the filetype is only evaluated when the plugin is lazy-loaded, it only takes the syntax of the first file. So if I'm editing both a html and a markdown at the same time I can't go between them and expect Pastify to paste the correct option.

**Comment by superzanti** [comment]
Note: I fixed this in my [pull request](https://github.com/TobinPalmer/pastify.nvim/pull/9)

**Comment by TobinPalmer** [comment]
This issue was solved by @geeker-one amazing PR.
